[server]
port = 8501
address = "0.0.0.0"
baseUrlPath = "/ARA"
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
base = "dark"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[runner]
magicEnabled = true
fastReruns = true
